### ISSUE TITLE
按教程，无法创建 Devtools 面板

### ISSUE THREAD

**Issue by liuyinzhong** [mulingyuer/chrome-extension-template#1]
我想用这个教程，创建一个开发 F12 Devtools 面板的工程。因为网站生产环境是加密的。每次在网络请求里拿到密文。在手动解密，很不方便。所以我想开发一个用于监听网络请求，在请求前后进行解密的操作。在把解密后的数据JSON化。供于我明文查看。但是按照教程走后，F12 打开控制台是出现了我的面板，但是面板是白屏，无任何内容。请问我这是哪里写错了吗？
![Snipaste_2024-11-25_18-29-19](https://github.com/user-attachments/assets/8084217f-6008-48ac-8654-dd26ddea2371)

**Comment by liuyinzhong** [comment]
![image](https://github.com/user-attachments/assets/9d8577b6-3d35-4ac2-b2e9-d46d27d8df8e)

**Comment by mulingyuer** [comment]
我估计是你没看完我那篇关于这个模板的教程，你这里有两个明显错误：
1. 所有的文件path，需要使用绝对路径，你的 `./index.html`不对；
2. 所有的html页面，如果想要被检查到，要么走vite多页面入口，要么配置manifest中为完全静态资源，你的`./index.html`根本找不到资源文件；

我尝试弄了一个devtool的页面示例，已经更新到仓库了，你可以拉取参考一下，然后目前谷歌浏览会有一个bug，会报错Unknown VE context，看上去应该是浏览器自身的问题，不是很确定，因为这个报错并不影响功能，也能查到对应的issues：https://issuetracker.google.com/issues/369319572

你自个研究看看

**Comment by liuyinzhong** [comment]
懂了。是我的问题，感谢
